import { StyleSheet, Platform, StatusBar } from 'react-native';
import { normalize } from '../../../utils/dimensions';

export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    resizeMode: 'cover',
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  card: {
    backgroundColor: '#FFF',
    borderRadius: normalize(12),
    padding: normalize(20),
    width: '90%',
    alignItems: 'center',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 6,
    position: 'absolute',
    top: '50%',
    transform: [{ translateY: -normalize(150) }],
  },
  imageContainer: {
    position: 'relative',
    width: normalize(120),
    height: normalize(120),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: normalize(15),
  },
  contactImage: {
    width: '100%',
    height: '100%',
    borderRadius: normalize(60),
  },
  editIcon: {
    position: 'absolute',
    bottom: -5,
    right: -5,
    backgroundColor: '#00ACAC',
    borderRadius: normalize(20),
    padding: normalize(6),
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
  },
  name: {
    fontSize: normalize(22),
    fontWeight: 'bold',
    color: '#333',
    marginBottom: normalize(8),
  },
  phone: {
    fontSize: normalize(18),
    color: '#666',
    marginBottom: normalize(4),
  },
  relation: {
    fontSize: normalize(16),
    color: '#888',
    fontStyle: 'normal',
    marginBottom: normalize(10),
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderRadius: normalize(12),
    padding: normalize(20),
    width: '90%',
    alignItems: 'center',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 6,
    marginTop: normalize(20),
    position: 'absolute',
    top: '45%',
    transform: [{ translateY: -normalize(200) }],
  },
  modalImage: {
    width: normalize(100),
    height: normalize(100),
    borderRadius: normalize(50),
  },
  input: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#ccc',
    padding: normalize(10),
    marginVertical: normalize(8),
    borderRadius: normalize(8),
    fontSize: normalize(16),
    backgroundColor: '#FFFFFF',
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00ACAC',
    paddingVertical: normalize(12),
    paddingHorizontal: normalize(24),
    borderRadius: normalize(8),
    marginTop: normalize(20),
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonText: {
    fontSize: normalize(18),
    color: '#FFF',
    fontWeight: 'bold',
  },
  // En ContactDetailsStyles.ts
  backButton: {
    position: 'absolute',
    top: 20,
    left: 20,
    zIndex: 1,
    padding: 10,
  },
});