// HomeStyles.ts
import { StyleSheet, Platform, StatusBar } from 'react-native';
import { normalize, screenWidth } from '../../utils/dimensions';

export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  title: {
    color: '#FFF',
    fontSize: normalize(24),
    fontWeight: '400',
    textAlign: 'center',
    marginTop: normalize(30),
    marginBottom: normalize(30),
    textShadowColor: 'rgba(255, 214, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  content: {
    flex: 1,
    padding: normalize(20),
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: normalize(100)
  },
  buttonContainer: {
    position: 'relative',
    width: normalize(400),
    height: normalize(400),
    justifyContent: 'center',
    alignItems: 'center',
  },
  linesContainer: {
    position: 'absolute',
    width: normalize(400),
    height: normalize(400),
    top: 0,
    left: 0,
  },
  nearbyPeopleContainer: {
    position: 'absolute',
    width: normalize(380),
    height: normalize(380),
    justifyContent: 'center',
    alignItems: 'center',
  },
  personBubble: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    width: normalize(60),
    height: normalize(80),
  },
  personImage: {
    width: normalize(50),
    height: normalize(50),
    borderRadius: normalize(25),
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    backgroundColor: '#FFF',
    shadowColor: "#FFFFFFFF",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 8,
  },
  personName: {
    color: '#FFF',
    fontSize: normalize(12),
    marginTop: normalize(4),
    textAlign: 'center',
    textShadowColor: 'rgba(255, 214, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  outerButton: {
    width: normalize(260),
    height: normalize(260),
    borderRadius: normalize(300),
    backgroundColor: 'rgba(245, 245, 250, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 10,
    shadowColor: "#FFFFFFFF",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.4,
    shadowRadius: 15,
    transform: [{ scale: 1 }],
  },
 outerButtonActive: {
    width: normalize(80), // Reducido de 220 a 160
    height: normalize(80), // Reducido de 220 a 160
    transform: [{ scale: 0.85 }],
    shadowColor: "#FFFFFFFF",
    shadowOpacity: 0.6,
    shadowRadius: 20,
  },
  innerButton: {
    width: normalize(220),
    height: normalize(220),
    borderRadius: normalize(200),
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: "#FF7E7B",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  buttonContent: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    gap: normalize(8),
  },
  subtitleText: {
    color: 'white',
    fontSize: normalize(16),
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  innerButtonActive: {
    width: normalize(70), // Reducido de 170 a 120
    height: normalize(70), // Reducido de 170 a 120
    shadowOpacity: 0.7,
    shadowRadius: 15,
  },
  buttonText: {
    color: 'white',
    fontSize: normalize(70),
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  buttonTextActive: { // Nuevo estilo para el texto cuando está activo
    fontSize: normalize(22), // Texto más pequeño cuando está activo
  },
  cancelButton: {
    marginTop: normalize(2),
    padding: normalize(8),
    paddingHorizontal: normalize(16),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: normalize(15),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  cancelText: {
    color: '#FFF',
    fontSize: normalize(14),
    fontWeight: '600',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  emergencyTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF', // Blanco puro
    padding: normalize(10),
    borderRadius: normalize(30),
    marginTop: normalize(20),
    width: screenWidth * 0.4,
    elevation: 5,
    shadowColor: "#FFFFFFFF",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    gap: normalize(10),
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  emergencyText: {
    color: '#FF0000FF',
    fontSize: normalize(24),
    fontWeight: '500',
    marginLeft: normalize(10),
    textShadowColor: 'rgba(179, 2, 2, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  countdownText: {
    color: 'white',
    fontSize: normalize(80),
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    marginBottom: normalize(5),
  },
  countdownContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  resolveButton: {
    width: screenWidth * 0.4,
    marginTop: normalize(30),
    elevation: 5,
    shadowColor: "#FFFFFFFF",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    borderRadius: normalize(30),
  },
  resolveGradient: {
    padding: normalize(12),
    borderRadius: normalize(30),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  resolveText: {
    color: '#FFFFFF',
    fontSize: normalize(20),
    fontWeight: '500',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  }
});